### ISSUE TITLE
Texture without .xpm return an invalid color

### ISSUE THREAD

**Issue by antoineverin** [TheSecretOrganization/cub3d#19]
```
NO ./texture/test
SO ./texture/test
WE ./texture/test
EA ./texture/test
```
print the error 
```
Error
Color's must be compose by three integer, there value must be between 0 and 255
```

**Comment by Neffi42** [comment]
Yes beacause it is not considered as a texture. Would you prefer a more generic error in the first place ?

**Comment by antoineverin** [comment]
> Yes beacause it is not considered as a texture. Would you prefer a more generic error in the first place ?

That could be a more explicit error message indead, if it's not that hard to implement
